### ISSUE TITLE
license issues with is-macro crate (moved from kdy1/is-macro?)

### ISSUE THREAD

**Issue by decathorpe** [dudykr/ddbase#25]
It looks like the is-macro crate was moved into this repository from https://github.com/kdy1/is-macro.

There are some problems with the versions that have recently been published to crates.io:

- the license text is no longer included with published crates. this is required by the MIT license (and the Apache-2.0 license, but see next point)
- the crate used to be licensed as MIT, but it is now listed as Apache-2.0. relicensing the crate like this without asking previous contributors is not OK.

**Comment by kdy1** [comment]
I think contributions were small enough

**Comment by decathorpe** [comment]
Fair enough, thank you for adding the license text! Would it be possible to publish a new release with this change as well?

**Comment by kdy1** [comment]
Did it, thank you for the reminder

**Comment by decathorpe** [comment]
Thanks a lot!
