### ISSUE TITLE
`Inflector` is archived

### ISSUE THREAD

**Issue by smoelius** [dudykr/ddbase#48]
Hello. I came here from [`is-macro`](https://docs.rs/is-macro/0.3.6/is_macro/), which relies on `Inflector`, which now archived:
- https://github.com/dudykr/ddbase/blob/f135e90fd54c8bddf91d5f84410ded8b22c857a8/Cargo.toml#L19
- https://github.com/whatisinternet/inflector

As an unrelated aside, the Dudy organization lists https://dudy.dev/ as its url, but that url 404s.

**Comment by kdy1** [comment]
I think we can use `heck` instead
